version: 0.2

phases: 
    # install:
    #     commands:
    #         - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #         - unzip awscliv2.zip
    #         - sudo ./aws/install
    pre_build:
        commands:
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 791073934047.dkr.ecr.us-east-1.amazonaws.com/cloudzone-lab
    build:
        commands:
            - echo "Build started on `date`"
            - pwd
            - cd  CICD/dockerImage
            - docker image build -t 791073934047.dkr.ecr.us-east-1.amazonaws.com/cloudzone-lab:latest .
    post_build:
        commands:
            - echo "Build completed on `date`"
            - docker push 791073934047.dkr.ecr.us-east-1.amazonaws.com/cloudzone-lab:latest
            
